package io.lhysin.order.exception

class ChaosException(message: String) : RuntimeException(message)